### ISSUE TITLE
Update to use shelljs's `chmod`

### ISSUE THREAD

**Issue by JamesMGreene** [JamesMGreene/grunt-chmod#1]
Update to use [ShellJS](https://github.com/arturadib/shelljs)'s [`chmod`](https://github.com/arturadib/shelljs#chmodoctal_mode--octal_string-file) instead of Node's built-in `fs.chmodSync`.

In reality, ShellJS is utilizing `fs.chmodSync` under the covers _but_ they also allow a symbolic mode input (i.e. `a+rx`) &mdash; which I'm sure many non-Windows devs would appreciate &mdash; in addition to the normal octal module input (i.e. `755`).

**Comment by rezonant** [comment]
+1, shelljs also supports "X" (representing directory execute permission, so you can set only directories as executable), something that appears to be impossible with grunt-chmod currently
